# -*- coding: utf-8 -*-
"""Updated FInal SP Code (Colab run)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bJ82eBTkos700LeymGUg94iZjRFwnLLy
"""

# #importing the libraries
# !pip install patchify
# !pip install segmentation_models

# !pip install -U -q segmentation-models
# !pip install -q tensorflow
# !pip install -q keras

import tensorflow as tf
print("TensorFlow version:", tf.__version__)
print("GPU available:", tf.config.list_physical_devices('GPU'))

physical_devices = tf.config.list_physical_devices('GPU')
if len(physical_devices) > 0:
    tf.config.experimental.set_memory_growth(physical_devices[0], True)
    print("GPU memory growth enabled.")

#!nvidia-smi

device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

import os

os.environ["CUDA_VISIBLE_DEVICES"] = "0"
os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'

print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

physical_devices = tf.config.experimental.list_physical_devices('GPU')
if len(physical_devices) > 0:
    tf.config.experimental.set_memory_growth(physical_devices[0], True)

policy = tf.keras.mixed_precision.Policy('mixed_float16')
tf.keras.mixed_precision.set_policy(policy)

!pip install -U -q segmentation-models
!pip install -q tensorflow==2.2.1
!pip install -q keras==2.5
import os
os.environ["SM_FRAMEWORK"] = "tf.keras"

from tensorflow import keras

import os
import cv2
import numpy as np
import segmentation_models as sm
# from patchify import patchify
from PIL import Image
from tensorflow.keras.metrics import MeanIoU
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from matplotlib import pyplot as plt
scaler=MinMaxScaler()

# from google.colab import drive
# drive.mount('/content/drive')

import glob
import os
from concurrent.futures import ThreadPoolExecutor
from cv2 import imread

image_dir = '/content/drive/MyDrive/SAR patches/data patches/'
mask_dir = '/content/drive/MyDrive/SAR patches/mask patches/'

image_files = glob.glob(os.path.join(image_dir, '*.png'))
mask_files = glob.glob(os.path.join(mask_dir, '*.png'))

with ThreadPoolExecutor() as executor:
    imageset = list(executor.map(imread, image_files))
    maskset = list(executor.map(imread, mask_files))

#Now converting those two datasets into numpy array
imageset=np.array(imageset)
maskset=np.array(maskset)

print(imageset.shape)
print(maskset.shape)

#Now visualizing some images and their corresponding masks for sanity check
import random
patch_size = 512
image_num=random.randint(0,len(imageset))
plt.figure(figsize=(12, 6))
plt.subplot(121)
plt.imshow(np.reshape(imageset[image_num], (patch_size, patch_size, 3)))
plt.subplot(122)
plt.imshow(np.reshape(maskset[image_num], (patch_size, patch_size, 3)))
plt.show()

#Now Hex to RGB Conversion
value=int('3C',base=16)
print(value)

def fill_values(image):
    color_map = {
        (0, 0, 0): 0,       # BLACK
        (0, 0, 255): 1,     # BLUE
        (0, 255, 255): 2,   # AQUA
        (255, 0, 0): 3,     # RED
        (255, 255, 0): 4    # YELLOW
    }

    label_image = np.zeros((image.shape[0], image.shape[1]))

    for i in range(image.shape[0]):
        for j in range(image.shape[1]):
            pixel = tuple(image[i, j])
            if pixel in color_map:
                label_image[i, j] = color_map[pixel]

    return label_image

label_img = []
for i in range(2744):
  n = fill_values(maskset[i])
  # if i % 100 == 0:
  #   print('Done:', i) #to track progress
  label_img.append(n)

print(maskset.shape)

with tf.device('/device:GPU:0'):
    #Now we will convert all the masks to labels
    labels=[]
    for i in range(2744):
      temp_label=label_img[i]
      labels.append(temp_label)
    #Now converting labels into a numpy array
    labels=np.array(labels)
    labels=np.expand_dims(labels,axis=3)

    print("Unique labels in this dataset are ",np.unique(labels))
    print(labels.shape)

#Another sanity check
import random
import numpy as np
print(labels.shape)
image_number = random.randint(0, len(imageset))
plt.figure(figsize=(12, 6))
plt.subplot(121)
plt.imshow(imageset[7])
plt.subplot(122)
plt.imshow(labels[7][:,:,0])
plt.show()

tf.config.experimental.set_memory_growth(tf.config.experimental.list_physical_devices('GPU')[0], True)

import numpy as np

with tf.device('/device:GPU:0'):
    # Assuming you already have the 'labels' array defined
    num_classes = len(np.unique(labels))
    print(num_classes)

    # One-hot encoding using vectorized operations
    labels_flat = labels.reshape(-1)  # Flatten the labels array
    labels_cat = np.zeros((labels_flat.shape[0],))
    labels_cat[np.arange(labels_flat.shape[0])] = labels_flat
    labels_cat = labels_cat.reshape(labels.shape)

    # 'labels_cat' now contains the one-hot encoded labels with shape 50x512x512x1



    print(labels_cat.shape)

import numpy as np

def one_hot_encode(labels, num_classes):
    # Convert labels to integer type
    labels = labels.astype(int)
    # Initialize an all-zero matrix of shape (len(labels), num_classes)
    one_hot = np.zeros((labels.size, num_classes))
    # Set a 1 at the index that matches each label
    one_hot[np.arange(labels.size), labels.flatten()] = 1
    return one_hot

num_classes = 5
print(num_classes)
labels_cat = one_hot_encode(labels, num_classes)

# Reshape the result back to the original shape, but with an added one-hot dimension
labels_cat = labels_cat.reshape(*labels.shape[:-1], num_classes)

print(labels_cat.shape)

import numpy as np

test_size = 0.20

num_test = int(test_size * imageset.shape[0])

# Shuffle the data indices.
indices = np.random.permutation(imageset.shape[0])

test_idx, train_idx = indices[:num_test], indices[num_test:]


x_train, x_test = imageset[train_idx], imageset[test_idx]
y_train, y_test = labels_cat[train_idx], labels_cat[test_idx]

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

image_dataset=[]
mask_dataset=[]
labels=[]

#Now determining loss function and weights
weights=[0.1666,0.1666,0.1666,0.16666,0.16666,0.16666]

dice_loss=sm.losses.DiceLoss(class_weights=weights)
focal_loss=sm.losses.CategoricalFocalLoss()
total_loss=dice_loss+(1*focal_loss)

img_height=x_train.shape[1]
img_width=x_train.shape[2]
img_channels=x_train.shape[3]
#Checking everything
print(x_train.shape)

from keras.models import Model
from keras.layers import Input, Conv2D, MaxPooling2D, UpSampling2D, concatenate, Conv2DTranspose, BatchNormalization, Dropout, Lambda
from keras import backend as K

def jacard_coef(y_true, y_pred):
    y_true_f = K.flatten(y_true)
    y_pred_f = K.flatten(y_pred)
    intersection = K.sum(y_true_f * y_pred_f)
    return (intersection + 1.0) / (K.sum(y_true_f) + K.sum(y_pred_f) - intersection + 1.0)



################################################################
with tf.device('/device:GPU:0'):
    def multi_unet_model(n_classes=5, IMG_HEIGHT=512, IMG_WIDTH=512, IMG_CHANNELS=3):
    #Build the model
        inputs = Input((IMG_HEIGHT, IMG_WIDTH, IMG_CHANNELS))
        s = Lambda(lambda x: x / 255)(inputs)   #No need for this if we normalize our inputs beforehand
        s = inputs

        #Contraction path
        c1 = Conv2D(16, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(s)
        c1 = Dropout(0.2)(c1)  # Original 0.1
        c1 = Conv2D(16, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c1)
        p1 = MaxPooling2D((2, 2))(c1)

        c2 = Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(p1)
        c2 = Dropout(0.2)(c2)  # Original 0.1
        c2 = Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c2)
        p2 = MaxPooling2D((2, 2))(c2)

        c3 = Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(p2)
        c3 = Dropout(0.2)(c3)
        c3 = Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c3)
        p3 = MaxPooling2D((2, 2))(c3)

        c4 = Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(p3)
        c4 = Dropout(0.2)(c4)
        c4 = Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c4)
        p4 = MaxPooling2D(pool_size=(2, 2))(c4)

        c5 = Conv2D(256, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(p4)
        c5 = Dropout(0.3)(c5)
        c5 = Conv2D(256, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c5)

        #Expansive path
        u6 = Conv2DTranspose(128, (2, 2), strides=(2, 2), padding='same')(c5)
        u6 = concatenate([u6, c4])
        c6 = Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(u6)
        c6 = Dropout(0.2)(c6)
        c6 = Conv2D(128, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c6)

        u7 = Conv2DTranspose(64, (2, 2), strides=(2, 2), padding='same')(c6)
        u7 = concatenate([u7, c3])
        c7 = Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(u7)
        c7 = Dropout(0.2)(c7)
        c7 = Conv2D(64, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c7)

        u8 = Conv2DTranspose(32, (2, 2), strides=(2, 2), padding='same')(c7)
        u8 = concatenate([u8, c2])
        c8 = Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(u8)
        c8 = Dropout(0.2)(c8)  # Original 0.1
        c8 = Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c8)

        u9 = Conv2DTranspose(16, (2, 2), strides=(2, 2), padding='same')(c8)
        u9 = concatenate([u9, c1], axis=3)
        c9 = Conv2D(16, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(u9)
        c9 = Dropout(0.2)(c9)  # Original 0.1
        c9 = Conv2D(16, (3, 3), activation='relu', kernel_initializer='he_normal', padding='same')(c9)

        outputs = Conv2D(n_classes, (1, 1), activation='softmax')(c9)

        model = Model(inputs=[inputs], outputs=[outputs])

        #NOTE: Compile the model in the main program to make it easy to test with various loss functions
        model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

        model.summary()

        return model

#Now defining metrices for your evaluation
metrics=['accuracy', jacard_coef]

model = multi_unet_model()

#Now running the model
with tf.device('/device:GPU:0'):
    history1=model.fit(x_train,y_train,batch_size=4,verbose=1,epochs=100,validation_data=(x_test,y_test), shuffle=False)

import numpy as np
from keras import backend as K

def dice_coefficient(y_true, y_pred):
    y_true_f = K.flatten(y_true)
    y_pred_f = K.flatten(y_pred)
    intersection = K.sum(y_true_f * y_pred_f)
    return (2. * intersection + K.epsilon()) / (K.sum(y_true_f) + K.sum(y_pred_f) + K.epsilon())

def iou_coefficient(y_true, y_pred, smooth=1):
    intersection = K.sum(K.abs(y_true * y_pred), axis=-1)
    union = K.sum(y_true,-1) + K.sum(y_pred,-1) - intersection
    iou = K.mean((intersection + smooth) / (union + smooth), axis=-1)
    return iou

# Assuming multi_unet_model is your trained model
y_pred = model.predict(x_test)

# Convert one-hot encoded labels to class labels
y_test_argmax = np.argmax(y_test, axis=-1)
y_pred_argmax = np.argmax(y_pred, axis=-1)

# Convert numpy arrays to TF tensors
y_test_argmax_tf = tf.convert_to_tensor(y_test_argmax, dtype=tf.float32)
y_pred_argmax_tf = tf.convert_to_tensor(y_pred_argmax, dtype=tf.float32)

# Calculate and print Dice Coefficient
dice_coef = dice_coefficient(y_test_argmax_tf, y_pred_argmax_tf)
print('Dice Coefficient: ', K.get_value(dice_coef))

# Calculate and print IoU Coefficient
iou_coef = iou_coefficient(y_test_argmax_tf, y_pred_argmax_tf)
print('IoU Coefficient: ', K.get_value(iou_coef))

#  from sklearn.metrics import f1_score, confusion_matrix
# y_pred = model.predict(x_test)
# # Reshape y_test and y_pred into 2D arrays
# y_test_2d = y_test.reshape((-1, 5))
# y_pred_2d = y_pred.reshape((-1, 5))

# # Convert y_test_2d and y_pred_2d to integer labels
# y_test_labels = y_test_2d.argmax(axis=1)
# y_pred_labels = y_pred_2d.argmax(axis=1)

# # Calculate the F1 score and confusion matrix
# f1 = f1_score(y_test_labels, y_pred_labels, average=None)
# confusion_mat = confusion_matrix(y_test_labels, y_pred_labels)

# print("F1 Score Matrix:")
# print(f1)
# print("\nConfusion Matrix:")
# print(confusion_mat)

from matplotlib import pyplot as plt

#Now visualizing training and validation loss
train_loss=history1.history['loss']
val_loss=history1.history['val_loss']
epochs=range(1,len(train_loss)+1)
plt.plot(epochs,train_loss, 'y', label='Training loss')
plt.plot(epochs, val_loss, 'r', label='Validation loss')
plt.title('Training and validation loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()