# -*- coding: utf-8 -*-
"""sar-patches-maker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IFvr1aztT8lRbE0OxJBsrhS8nklER8Od
"""

!pip install patchify
!pip install segmentation models.

# from google.colab import drive
# drive.mount('/content/drive')

import os
import cv2
import numpy as np
from patchify import patchify
from PIL import Image
from sklearn.preprocessing import StandardScaler,MinMaxScaler

scaler=MinMaxScaler()
patch_size=512
MAX_PATCHES = 10000

Image.MAX_IMAGE_PIXELS = None

def create_patches(path,store_path,mask_path,mask_store_path):
    image=cv2.imread(path,1)
    mask=cv2.imread(mask_path,1)

    print('Image:', image.shape)
    print('Mask:', mask.shape)

    size_x=(image.shape[1]//patch_size)*patch_size
    size_y=(image.shape[0]//patch_size)*patch_size

    image=Image.fromarray(image)
    mask=Image.fromarray(mask)

    image=image.crop((0,0,size_x,size_y))
    mask=mask.crop((0,0,size_x,size_y))

    image=np.array(image)
    mask=np.array(mask)

    print("Now patchifying image and masks")
    patch_images=patchify(image,patch_size=(patch_size,patch_size,3),step=512)
    patch_masks=patchify(mask,patch_size=(patch_size,patch_size,3),step=512)

    counter=0

    for i in range(patch_images.shape[0]):
        for j in range(patch_images.shape[1]):
            if counter < MAX_PATCHES:
                single_patch_img=patch_images[i,j,:,:]
                single_patch_mask=patch_masks[i,j,:,:]

                single_patch_img=single_patch_img[0]
                single_patch_mask=single_patch_mask[0]

                writing=store_path+str(counter)+'.png'
                mwriting=mask_store_path+str(counter)+'.png'
                cv2.imwrite(writing,single_patch_img)
                cv2.imwrite(mwriting,single_patch_mask)

                counter+=1
            else:
                break
        if counter >= MAX_PATCHES:
            break
    print(f"Saved {counter} patches.")

if __name__=='__main__':
    mp=r'/content/drive/MyDrive/DhakaGTAGG.tif'
    ip=r'/content/drive/MyDrive/convertedDhakaSARV21.png'
    store=r'/content/drive/MyDrive/SAR patches/data patches//'
    mstore=r'/content/drive/MyDrive/SAR patches/mask patches//' #replace with path where you want to store the patches

    create_patches(ip,store,mp,mstore)